#!/bin/sh
SESSION_NAME='cmus'
SCREENRC="${HOME}/dotfiles/config/256color.screenrc"
SCREEN='env TERM=screen-256color screen'
CMUS='env TERM=screen-256color cmus'
if ! ${SCREEN} -r -D ${SESSION_NAME} > /dev/null; then
  ${SCREEN} -S ${SESSION_NAME} -c ${SCREENRC} ${CMUS}
fi
