#!/bin/sh
#
# Rubocop patch for syntastic
# from: https://gist.github.com/lcd047/96138909015f2f8d2d36
#
rubocop() {
  if bundle exec rubocop --version &> /dev/null; then
    bundle exec rubocop "$@"
  else
    rbenv exec rubocop "$@"
  fi
}

if [ $# -eq 1 -a x"$1" = x--version ]; then
  rubocop "$@" 2>&1 | \
    sed '/warning: parser\/current is loading parser\/ruby[0-9]*, which recognizes/d;
         /warning: [0-9.]*-compliant syntax, but you are running [0-9.]/d'
else
  rubocop "$@"
fi
