#!/bin/sh

function usage() {
  echo "Usage: `basename $0` URL"
  echo
  exit 1
}

if [ $# -lt 1 ]; then
  usage
fi

video_full_url=$1
video_url=`echo ${video_full_url} | sed -E 's/v=([^&]*).*/v=\1/'`

youtube-dl --extract-audio --audio-format mp3 --output "${HOME}/youtube/%(id)s_%(title)s.%(ext)s" "${video_url}"
